# Generated by Django 4.1.4 on 2022-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(blank=True, max_length=25, null=True)),
                ('referal', models.CharField(blank=True, max_length=500, null=True)),
                ('referal_user', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('new_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('otp', models.CharField(blank=True, max_length=20, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
            ],
        ),
    ]
