# Generated by Django 4.1.4 on 2022-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_internationallogisticcompany_loaderservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('kara', 'Kara'), ('manipulyator', 'Manipulyator'), ('evacuator', 'Evacuator')], max_length=100, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=5000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=5000, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
