# Generated by Django 4.1.4 on 2022-12-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_loaderequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customs',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customs',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
