# Generated by Django 4.1.4 on 2022-12-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_customs_latitude_customs_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
            ],
        ),
    ]
