# Generated by Django 4.1.4 on 2022-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
