# Generated by Django 4.1.4 on 2023-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_interest_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(null=True, to='backend.category'),
        ),
    ]
