# Generated by Django 4.1.4 on 2023-01-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderequipment',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region'),
        ),
    ]
