# Generated by Django 4.1.4 on 2023-01-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_loaderservice_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customs',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region'),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_ru',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_uz',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
