# Generated by Django 4.1.4 on 2023-01-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_customs_region_wearhouse_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticservice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='logisticservice',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='logisticservice',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='logisticservice',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='logisticservice',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='logisticservice',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='logisticservice',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logisticservice',
            name='tonna',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='logisticservice',
            name='type',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
