# Generated by Django 4.1.5 on 2023-01-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_postservice_latitude_postservice_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customs',
            name='address_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='customs',
            name='address_ru',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='customs',
            name='address_uz',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_ru',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='address_uz',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
