# Generated by Django 4.1.4 on 2023-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_logisticservice_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticservice',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
