# Generated by Django 4.1.4 on 2023-01-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_logisticservice_is_international'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('legalname_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('legalname_en', models.CharField(blank=True, max_length=500, null=True)),
                ('legalname_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('address_uz', models.TextField(blank=True, max_length=5000, null=True)),
                ('address_en', models.TextField(blank=True, max_length=5000, null=True)),
                ('address_ru', models.TextField(blank=True, max_length=5000, null=True)),
                ('contacts', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
