# Generated by Django 4.1.4 on 2023-01-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_sertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
