# Generated by Django 4.1.5 on 2023-03-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_customs_address_en_remove_customs_address_ru_and_more'),
        ('backend', '0027_customs_contact'),
    ]

    operations = [
    ]
