# Generated by Django 4.1.5 on 2023-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_merge_20230304_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaderequipment',
            name='type',
            field=models.CharField(choices=[('kara', 'Kara'), ('manipulyator', 'Manipulyator'), ('evacuator', 'Evacuator'), ('kran', 'kran')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='backend.category'),
        ),
    ]
