# Generated by Django 4.1.5 on 2023-03-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_loaderequipment_type_alter_user_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearhouse',
            old_name='latitude',
            new_name='description_kr',
        ),
        migrations.RenameField(
            model_name='wearhouse',
            old_name='longitude',
            new_name='name_kr',
        ),
        migrations.RemoveField(
            model_name='wearhouse',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='wearhouse',
            name='address_uz',
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='place',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wearhouse',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wearhouse',
            name='description_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wearhouse',
            name='description_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
