# Generated by Django 4.1.5 on 2023-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_wearhouse_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaderequipment',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='loaderequipment',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='loaderequipment',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='loaderequipment',
            name='name_kr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loaderequipment',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaderequipment',
            name='tonn',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loaderequipment',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wearhouse',
            name='place',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
